before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - github:
      owner: maximepeschard
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/maximepeschard/kafkadog
    description: Kafka consumer/producer CLI
